In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

<!-- como configurar yaml para que index sea scroleable hacia abajo, agregar animacion conforme aparecen graficas, investigar y despues preguntar a IA (copilot gh) -->

<!-- inveestigar como configurar agente para que llene automaticamente ai-log.md de forma transparente, o simplmente cada quien es responsable de poner / decirle al agente que lo ponga -->

indicadores ODS 6 que no reporta México:

https://sdgs.un.org/goals/goal6#targets_and_indicators

https://agenda2030.mx/ODSGoalSelected.html?ti=T&cveArb=ODS0060&goal=0&lang=es#/ind



indicadores no desagregados por estado (INEGI ninguno por municipio?)

 6.3.1
Proporción de aguas residuales tratadas de manera adecuada  G 
 
6.3.2.
Proporción de cuerpos de agua con buena calidad de agua  G  

CONAGUA sí reporta, buscar (bioenergía)

 6.4.1
Cambio en la eficiencia del uso del agua a lo largo del tiempo  G 
 
6.4.2
Nivel de estrés hídrico: extracción de agua dulce como proporción de los recursos disponibles de agua dulce.  G  

 6.5.1.
Grado de implementación de la gestión integrada de los recursos hídricos  G 
 
6.5.2.
Proporción de la superficie de cuencas transfronterizas sujetas a arreglos operacionales para la cooperación en materia de aguas  

 6.6.1.a
Cambio en el área de lagos y ríos permanentes (%)  G 
 
6.6.1.b
Cambio en el área de lagos y ríos estacionales (%)  G 
 
6.6.1.c
Cambio en el área de manglares (%)  G 
 
6.6.1.d
Superficie del embalse como porcentaje de la superficie terrestre total (%)  G 
 
6.6.1.e
Área de humedales como porcentaje de la superficie terrestre total (%)  G



Gestión integral de los recursos hídricos a todos los niveles
6n.2.1
Grado de presión sobre el recurso hídrico de las zonas centro y norte del país  N 
 

¿cómo desagregar por municipio o cuenca?

¿qué otros indicadores hay sobre el agua? cómo se calcula "día cero"? hay alguna métrica que ayude a responder a la pregunta de "¿cuándo nos vamos a quedar sin agua?"?

6.n.1 no es lo mismo que 6.1.1? tiene otras metas? comparar objetivos cuantitativamente: poner líneas punteadas en gráficas

qué diferencias hay entre el indicador nacional y el global o estatal reportado en los indicadores globales? hay diferencias entre cómo se calculan los indicadores?

# comparacion 

6.4.2
Nivel de estrés hídrico: extracción de agua dulce como proporción de los recursos disponibles de agua dulce.  G  

Gestión integral de los recursos hídricos a todos los niveles
6n.2.1
Grado de presión sobre el recurso hídrico de las zonas centro y norte del país  N

757 cuencas hidrológicas

para desagregar, obtener estos datos por cuenca por año

1. escurrimiento natural medio superficial: ya incluido en disponibilidad superficial?
2. entradas y salidas de agua superficial de y hacia otros países
3. recarga de agua subterránea
4. caudal ecológico en los sistemas de cuencas 
5. descarga natural comprometida en acuíferos

ya se tiene:

1. disponibilidad superficial https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/9b0354df-90e3-4b8e-a656-31528f970fac
2. disponibilidad acuíferos https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/c9d72f33-5caf-4641-8620-155da91ba82c
3. volumen concesionado superficial (csurf) https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/e29b028e-d335-4c48-abe5-b2dbe8bcc2dc
4. volumen concesionado subterráneo (csub) https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/763c4995-8607-4c74-af0e-112c9c1f5e50

https://agenda2030.mx/ODSind.html?ind=ODS006000350020&cveind=407&cveCob=99&lang=es#/Indicator

$$estres=\frac{TFWW}{TRWR-EFR}\times 100\%$$

$TFWW=csurf+csub$ extracción total de agua dulce

$TRWR=IRWR+ERWR$ recursos renovables totales de agua dulce (interno + externo)

escurrimiento natural medio superficial, entradas y salidas de agua superficial de y hacia otros países, recarga de agua subterránea

$EFR=$ requisitos de caudales ambientales, cantidad y duración de de los caudales de agua dulce y niveles necesarios para sostener los ecosistemas acuáticos: caudal ecológico y descarga natural comprometida en acuíferos

superficial

2016: https://dof.gob.mx/nota_detalle.php%3Fcodigo%3D5443858%26fecha%3D07/07/2016#gsc.tab=0

 Cp.- Volumen medio anual de escurrimiento natural
Ar.- Volumen medio anual de escurrimiento desde la cuenca aguas arriba
Uc (a).- Volumen anual de extracción de agua superficial mediante títulos inscritos actualmente en el REPDA
Uc (b).- Volumen anual de extracción de agua superficial de títulos en proceso de inscripción en el REPDA
Uc (c).- Volumen anual correspondiente a las reservas, el caudal ecológico y las zonas reglamentadas
R.- Volumen anual de retornos
Im.- Volumen anual de importaciones
Ex.- Volumen anual de exportaciones
Ev.- Volumen medio anual de evaporación en embalses
Av.- Volumen medio anual de variación de almacenamiento en embalses
Ab.- Volumen medio anual de escurrimiento de la cuenca hacia aguas abajo
Rxy.- Volumen anual actual comprometido aguas abajo
D.- Disponibilidad media anual de agua superficial en la cuenca hidrológica

subterráneo

2022: https://www.dof.gob.mx/nota_detalle_popup.php?codigo=5708074

R: recarga total media anual; DNC: descarga natural comprometida; VEAS: volumen de extracción de aguas subterráneas; VCAS: volumen concesionado/asignado de aguas subterráneas; VEALA: volumen de extracción de agua en las zonas de suspensión provisional de libre alumbramiento y los inscritos en el Registro Nacional Permanente; VAPTYR: volumen de extracción de agua pendiente de titulación y/o registro en el REPDA; VAPRH: volumen de agua correspondiente a reservas, reglamentos y programación hídrica; DMA: disponibilidad media anual de agua del subsuelo. Las definiciones de estos términos son las contenidas en los numerales "3" (fracciones 3.10, 3.12, 3.18 y 3.25), y "4" (fracción 4.3), de la Norma Oficial Mexicana NOM-011-CONAGUA-2015.

$$s=\frac{TFWW}{TRWR-EFR}\times 100\%$$

$TFWW=Uca+VEAS+VCAS$$ extracción total de agua dulce

https://sinav30.conagua.gob.mx:8080/Estadistico/#/repda: REPDA por municipio: mejor usar este y desagregar los demás datos por municipio (o si no desagregar todo por estado)


volumen de agua dulce extraída de su fuente (ríos, lagos, acuíferos) para la agricultura, las industrias, y los servicios: solo estos usos?

"toma en cuenta" (suma) volúmenes concesionados de agua registrados en el Registro Público de Derechos de Agua (REPDA) e integrados en el Sistema Nacional de Información del Agua (SINA) con corte al 31 de diciembre de cada año

Uc (a).- Volumen anual de extracción de agua superficial mediante títulos inscritos actualmente en el REPDA: solo esta por municipio: entonces si esta en SINA 3.0
Uc (b).- Volumen anual de extracción de agua superficial de títulos en proceso de inscripción en el REPDA?

VEAS: volumen de extracción de aguas subterráneas; VCAS: volumen concesionado/asignado de aguas subterráneas: esta por acuifero, RHA

VEALA: volumen de extracción de agua en las zonas de suspensión provisional de libre alumbramiento y los inscritos en el Registro Nacional Permanente; VAPTYR: volumen de extracción de agua pendiente de titulación y/o registro en el REPDA?

¿cómo saber a qué cuenca o región hidrológica (RH) corresponde cada acuífero? municipiio? buscar esta información y complementar

https://sinav30.conagua.gob.mx:8080/Estadistico/#/acuiferos


$TRWR=IRWR+ERWR$ recursos renovables totales de agua dulce

agua renovable por estado (después incluir per cápita): https://sinav30.conagua.gob.mx:8080/Estadistico/#/aguaRenovable 


$IRWR$ recursos hídricos renovables internos

$ERWR$ recursos hídricos renovables externos

Cp escurrimiento natural medio superficial

Im.- Volumen anual de importaciones
Ex.- Volumen anual de exportaciones https://sinav30.conagua.gob.mx:8080/Estadistico/#/cuencas por cuenca hidrológica

R: recarga total media anual (subterránea) por acuífero https://sinav30.conagua.gob.mx:8080/Estadistico/#/acuiferos

$ERF$ requisitos de caudales ambientales

Ucc Volumen anual correspondiente a las reservas, el caudal ecológico y las zonas reglamentadas: no está en cuencas

DNC: descarga natural comprometida: por acuífero

así que comparar 2 opciones (hasta el menor grado de desagregacion que se pueda, desde 2015 hasta lo mas actual que haya):

1. tal cual en INEGI para comparar (desagregación difícil)
2. REPDA/agua renovable: 2020-2023
3. 2 pero restando ERF: no está en cuencas
4. grado de presión por RHA

Niveles de desagregación

Estado
Municipio


Región hidrológica administrativa (RHA)
Región hidrológica (RH)
Cuenca hidrológica


Ideal: todos
Posible: estado (se tienen que cortar pocos datos a vectores de estado, especialmente con segunda opción)


también comparar fuentes

Para el indicador ODS 6.4.2, internacionalmente se propone clasificar el nivel de estrés hídrico en tres categorías principales (niveles): bajo, alto y muy alto. No se han definido los umbrales para el indicador ya que podrían ser específicos del país, para reflejar las diferencias en el clima y los objetivos nacionales de gestión del agua. O también, alternativamente, se pueden proponer umbrales uniformes utilizando la literatura existente y teniendo en cuenta los requisitos ambientales del agua. Algunos de los valores de las variables involucradas en este indicador provienen de las publicación de las disponibilidades de agua superficial y agua subterránea que realiza la Conagua. Al interior de México, se ha implementado el indicador "Grado de Presión sobre los Recursos Hídricos", pero este indicador no descuenta los requerimientos ambientales del total de agua renovable, por lo que ambos indicadores se complementan.

## 1a. aproximación: grado de presión por RHA 2003-2022
geojson https://sinav30.conagua.gob.mx:8080/SINA/?opcion=base

In [18]:
anos = np.arange(2003,2022+1)
for ano in anos:
    f = f"../datos/Grado_de_Presion_{ano}.xlsx"
    if ano == 2003:
        gp = pd.read_excel(f,usecols=["Región Hidrológico-Administrativa","Grado de Presión (%)"])
        gp.columns = ["RHA",ano]
    else:
        gp_ano = pd.read_excel(f,usecols=["Grado de Presión (%)"])
        gp_ano.columns = [ano]
        gp[ano] = gp_ano[ano]
gp["RHA"] = gp["RHA"].str.replace(r"^\s*[IVXLCDM]+\s*[-.]?\s*", "", regex=True)
name_mapping = {
    "Península de Baja California": "Península De Baja California",
    'Cuencas Centrales del Norte': 'Cuencas Centrales Del Norte',
    "Península de Yucatán": "Península De Yucatán",
    'Aguas del Valle de México': 'Valle de México'
}
gp['RHA'] = gp['RHA'].replace(name_mapping)
gp

,RHA,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Península De Baja California,85.99,86.08,86.33,75.94,75.91,75.88,73.28,76.80,77.24,...,68.70,79.64,79.83,81.20,81.32,89.92,91.86,89.97,90.10,89.94
1,Noroeste,77.80,78.16,80.45,87.08,92.31,91.42,90.63,88.18,87.31,...,75.88,81.16,81.34,81.56,84.69,84.96,82.81,83.03,83.02,83.20
2,Pacífico Norte,42.08,42.23,41.24,40.04,40.49,40.74,40.62,40.04,40.07,...,39.43,41.93,42.08,40.59,40.42,40.46,40.05,40.23,40.44,40.51
3,Balsas,35.53,36.01,36.96,49.68,49.77,49.37,49.38,47.10,46.34,...,46.73,48.67,49.81,50.11,50.18,51.55,52.04,48.04,48.16,48.40
4,Pacífico Sur,4.15,3.89,3.93,3.94,4.10,4.12,4.15,4.37,4.44,...,4.67,5.04,5.09,5.09,5.12,5.15,5.49,5.44,5.44,5.45
5,Río Bravo,60.82,60.20,72.43,76.33,76.44,77.36,76.00,71.56,73.10,...,71.69,77.24,77.10,76.73,75.36,76.11,75.36,74.46,74.64,75.02
6,Cuencas Centrales Del Norte,54.47,54.76,55.20,45.36,49.29,48.61,48.70,45.33,46.07,...,46.63,48.42,48.39,48.38,47.65,47.85,47.53,80.89,82.78,83.03
7,Lerma-Santiago-Pacífico,32.72,35.72,36.03,40.19,40.76,41.46,41.93,42.36,41.04,...,41.99,43.57,44.82,45.42,45.18,45.63,45.84,45.64,45.72,45.91
8,Golfo Norte,19.16,19.29,19.53,17.91,18.36,18.58,18.99,18.15,19.25,...,20.55,21.00,20.42,20.78,21.13,21.38,22.00,21.97,22.03,21.02
9,Golfo Centro,4.45,4.51,4.63,4.80,5.10,5.17,5.19,5.13,5.15,...,5.18,5.73,5.85,8.58,6.43,6.61,6.80,6.75,6.77,6.42
10,Frontera Sur,1.25,1.26,1.26,1.29,1.35,1.39,1.40,1.36,1.40,...,1.37,1.62,1.73,1.45,1.73,1.72,1.78,1.68,1.69,1.70
11,Península De Yucatán,5.69,5.76,6.31,6.74,7.20,7.99,9.21,9.61,9.97,...,12.77,14.15,14.32,15.17,16.17,16.72,16.96,17.93,18.26,19.15
12,Valle de México,123.80,119.61,119.11,154.28,155.10,132.31,132.58,133.89,136.04,...,137.79,137.99,138.70,139.15,141.38,129.24,129.73,127.85,128.57,128.58

In [19]:
gp_largo = pd.melt(gp,id_vars=["RHA"],var_name="Año",value_name="Grado de presión (%)")
gp_largo["Año"] = gp_largo["Año"].astype(int)
geojson = "../datos/Región Hidrológico-Administrativa 2023.json"
fig = px.choropleth(gp_largo,geojson=geojson,locations="RHA",featureidkey="properties.rha",color="Grado de presión (%)",animation_frame="Año",color_continuous_scale="Viridis")
fig.update_geos(fitbounds="locations",visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [20]:
px.line(gp_largo,x="Año",y="Grado de presión (%)",color="RHA")

In [38]:
anos = np.arange(2005,2023+1)
for ano in anos:
    f = f"../datos/Agua_Renovable_RHA_{ano}.xlsx"
    if ano == 2005:
        arpcrha = pd.read_excel(f,usecols=["RHA","Agua Renovable per cápita (m³/habitante/año)"])
        arpcrha.columns = ["RHA",ano]
    else:
        arpcrh_ano = pd.read_excel(f,usecols=["Agua Renovable per cápita (m³/habitante/año)"])
        arpcrh_ano.columns = [ano]
        arpcrha[ano] = arpcrh_ano[ano]
name_mapping = {
    "Península de Baja California": "Península De Baja California",
    'Cuencas Centrales del Norte': 'Cuencas Centrales Del Norte',
    "Península de Yucatán": "Península De Yucatán",
    'Aguas del Valle de México': 'Valle de México'
}
arpcrha['RHA'] = arpcrha['RHA'].replace(name_mapping)
arpcrha

,RHA,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Río Bravo,1211.83784,24450.41608,6471.33192,6471.33192,5144.96005,1249.88786,1209.30227,1186.64851,1165.00768,1738.39138,1115.21275,1078.24279,1056.71348,1039.77443,1023.56395,1040.58997,1013.98078,999.26836,986.70000
1,Pacífico Sur,7977.07624,7750.35781,1100.72491,1100.72491,1234.05158,3160.83222,3100.40637,3054.86302,3011.44843,1134.86086,2911.63885,2874.01093,2837.34654,2802.10830,2768.28061,2920.26811,2704.74702,2674.32622,2661.40000
2,Balsas,2745.69998,6489.05499,165.30480,165.30480,3249.97108,6172.87764,5980.57530,5920.70532,5863.03154,2951.32172,5675.61545,5846.78765,5823.16453,5771.99761,5723.07639,5845.55496,5606.49777,5562.83166,5618.11651
3,Frontera Sur,25008.12733,143.87328,1897.60337,1897.60337,6472.72295,1987.09879,2025.47013,2002.34268,1980.36206,5729.65092,1835.94638,1817.11972,1799.48601,1782.77080,1766.77140,1915.36138,1879.21988,1863.86533,1909.83756
4,Noroeste,3294.41778,2028.64135,9968.63919,9968.63919,2040.47990,6813.95149,6599.70549,6541.42195,6488.16396,1895.83101,6040.85700,6054.52751,6017.31675,5982.67896,5950.51368,6057.85277,5983.51964,5956.89165,6011.53220
5,Golfo Centro,10931.71757,7927.66476,1642.12249,1642.12249,7952.33033,1144.03890,1091.73836,1077.26935,1063.37639,6083.63016,1003.81123,997.89199,1018.84473,1006.99540,995.64640,981.15820,989.47571,979.11117,1004.19272
6,Golfo Norte,4804.13544,3115.91062,3208.33311,3208.33311,1107.48695,1911.27119,1848.20128,1826.27448,1805.68426,1013.56249,1732.66863,1720.08316,1724.67927,1708.81577,1693.76470,981.46575,968.96862,961.33578,969.68711
7,Pacífico Norte,6408.81956,1130.52320,7441.63991,7441.63991,1886.67978,1527.47492,1555.79201,1534.93468,1515.30821,1469.07282,1451.22532,1427.33177,1418.81470,1403.89313,1389.67133,1374.20195,1370.00751,1357.40434,1358.46339
8,Valle de México,191.51395,2054.50844,1256.65846,1256.65846,1646.47384,5301.40139,5518.29161,5469.74903,5420.95488,5366.41189,5325.51347,5378.89701,5329.20023,5282.10464,5236.16525,5518.07568,5155.19124,5112.37026,4977.68580
9,Península De Yucatán,8010.92335,1663.32478,5154.53110,5154.53110,9936.64890,9348.80557,9305.33802,9225.75011,9148.93309,9075.08534,8993.22689,6165.10384,8795.69023,8731.60996,8669.90054,8919.72873,8613.30961,8557.74067,10517.84894
10,Lerma-Santiago-Pacífico,1846.23990,5200.52211,2048.82838,2048.82838,23835.45847,22392.91109,22477.19792,22185.10438,21905.84667,19078.13439,18852.05180,22692.45101,18775.50585,18571.27745,18374.89161,19818.84125,19328.45904,19140.28588,18421.83537
11,Cuencas Centrales Del Norte,1712.17888,1321.22538,24042.69756,24042.69756,7294.35904,7137.76865,7013.65150,6874.28811,6740.46923,6493.95836,6372.67708,6325.11735,6211.94280,6103.23815,5998.85841,5654.29333,5651.94425,5561.62842,3662.73889
12,Península De Baja California,1317.68713,10763.62335,7954.80432,7954.80432,163.99230,160.18933,154.65878,153.31564,152.01768,150.30770,148.41915,147.03597,144.41001,143.35990,142.35473,144.62765,142.27266,141.38051,140.54827

In [39]:
arpcrha_largo = pd.melt(arpcrha,id_vars=["RHA"],var_name="Año",value_name="Agua Renovable per cápita (m³/habitante/año)")
arpcrha_largo["Año"] = arpcrha_largo["Año"].astype(int)
geojson = "../datos/Región Hidrológico-Administrativa 2023.json"
fig = px.choropleth(arpcrha_largo,geojson=geojson,locations="RHA",featureidkey="properties.rha",color="Agua Renovable per cápita (m³/habitante/año)",animation_frame="Año",color_continuous_scale="Viridis")
fig.update_geos(fitbounds="locations",visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [40]:
px.line(arpcrha_largo,x="Año",y="Agua Renovable per cápita (m³/habitante/año)",color="RHA")

In [47]:
anos = np.arange(2017,2021+1)
for ano in anos:
    f = f"../datos/agua_renovable_estatal{ano}.xlsx"
    if ano == 2017:
        arpcedo = pd.read_excel(f,usecols=["Entidad Federativa","Agua Renovable per cápita (m³/habitante/año)"])
        arpcedo.columns = ["Estado",ano]
    else:
        arpcedo_ano = pd.read_excel(f,usecols=["Agua Renovable per cápita (m³/habitante/año)"])
        arpcedo_ano.columns = [ano]
        arpcedo[ano] = arpcedo_ano[ano]

name_mapping = {
    'Coahuila de Zaragoza': 'Coahuila',
    'Veracruz de Ignacio de la Llave': 'Veracruz',
}

arpcedo['Estado'] = arpcedo['Estado'].replace(name_mapping)
arpcedo

,Estado,2017,2018,2019,2020,2021
0,Aguascalientes,405.61414,389.01883,396.21842,380.50232,391.79025
1,Baja California,849.46600,831.94711,826.93254,823.51770,822.04654
2,Baja California Sur,1525.00525,1535.15290,1443.20038,1584.04120,1402.46850
3,Campeche,6218.94136,15255.04271,6046.29163,6377.35032,5993.16366
4,Coahuila,1141.02205,1041.35936,1116.31619,1112.07241,1106.69794
5,Colima,2887.23440,2842.06303,2799.48198,3016.18115,2777.84521
6,Chiapas,21099.08153,20953.11380,20618.78825,20996.15552,20678.66216
7,Chihuahua,3109.18681,3150.52390,3053.88463,3206.24718,3064.92530
8,Ciudad de México,73.08824,55.16537,73.46574,70.31264,74.32372
9,Durango,6999.31183,7439.15301,6874.23057,7052.25732,6938.69007
10,Guanajuato,657.65814,656.08584,648.34628,637.74607,647.71648
11,Guerrero,5813.91198,5879.01868,5758.82855,6077.88093,5860.57595
12,Hidalgo,2536.30087,2461.57919,2480.90880,2474.10721,2479.50332
13,Jalisco,1966.60251,1930.18854,1926.01053,1953.34569,1931.37032
14,México,275.63746,298.27139,268.24125,286.58100,266.04143
15,Michoacán,2712.01539,2706.11627,2679.39633,2718.41699,2708.24896
16,Morelos,940.22512,914.99937,919.74631,952.09860,914.98032
17,Nayarit,5250.46289,5004.97746,5074.93984,5516.01838,5028.44793
18,Nuevo León,850.56066,817.31201,828.13680,786.05257,825.34357
19,Oaxaca,13763.64422,13686.43894,13611.66441,13903.20439,13849.81054
20,Puebla,1802.72097,1820.17756,1770.90202,1772.44544,1785.75048
21,Querétaro,940.31062,982.36524,914.92609,835.39936,909.67124
22,Quintana Roo,1045.85510,4744.75752,992.50072,942.19798,949.91225
23,San Luis Potosí,3876.73902,3790.79299,3814.84097,3937.59419,3845.48409
24,Sinaloa,3262.99447,2867.87790,3212.40099,3290.20122,3183.98217
25,Sonora,2375.31614,2328.44028,2316.33480,2466.71444,2296.75116
26,Tabasco,13137.20307,12788.33365,12896.73393,13562.57615,12931.26845
27,Tamaulipas,2473.91060,2463.61084,2422.97731,2604.53727,2436.07638
28,Tlaxcala,661.04769,691.23548,644.31610,656.73356,639.13549
29,Veracruz,6325.35937,6251.90124,6240.33855,6572.38264,6323.29803
30,Yucatán,10038.94148,3194.78316,9798.54247,9398.68965,9573.16930
31,Zacatecas,2509.35437,2426.06437,2474.40900,2519.26762,2485.40125

In [48]:
arpcedo_largo = pd.melt(arpcedo,id_vars=["Estado"],var_name="Año",value_name="Agua Renovable per cápita (m³/habitante/año)")
arpcedo_largo["Año"] = arpcedo_largo["Año"].astype(int)
geojson = "https://raw.githubusercontent.com/angelnmara/geojson/master/mexicoHigh.json"
fig = px.choropleth(arpcedo_largo,geojson=geojson,locations="Estado",featureidkey="properties.name",color="Agua Renovable per cápita (m³/habitante/año)",animation_frame="Año",color_continuous_scale="Viridis")
fig.update_geos(fitbounds="locations",visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [49]:
px.line(arpcedo_largo,x="Año",y="Agua Renovable per cápita (m³/habitante/año)",color="Estado")

In [36]:
years = np.arange(2020, 2023 + 1)
for year in years:
    f = f"../datos/repda_estatal{year}.xlsx"

    if year == 2020:
        repda = pd.read_excel(f, usecols=["Estado", "Total por estado"])
        repda.columns = ["Estado", year]
        repda[year] = (
            repda[year]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.replace(r"[^\d.\-]", "", regex=True)
        )
        repda[year] = pd.to_numeric(repda[year], errors="coerce")
    else:
        repda_year = pd.read_excel(f, usecols=["Total por estado"])
        repda_year.columns = [year]
        repda_year[year] = (
            repda_year[year]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.replace(r"[^\d.\-]", "", regex=True)
        )
        repda_year[year] = pd.to_numeric(repda_year[year], errors="coerce")
        repda[year] = repda_year[year]

repda

                             Estado      2020      2021      2022      2023
0                    Aguascalientes    641.42    641.42    641.42    641.42
1                   Baja California   3472.88   3472.88   3472.88   3472.88
2               Baja California Sur    438.76    438.76    438.76    438.76
3                          Campeche   1840.23   1840.23   1840.23   1840.23
4              Coahuila de Zaragoza   2702.37   2702.37   2702.37   2702.37
5                            Colima   1774.54   1774.54   1774.54   1774.54
6                           Chiapas  62670.67  62670.67  62670.67  62670.67
7                         Chihuahua   7763.70   7763.70   7763.70   7763.70
8                  Ciudad de México    603.47    603.47    603.47    603.47
9                           Durango   1842.57   1842.57   1842.57   1842.57
10                       Guanajuato   4940.64   4940.64   4940.64   4940.64
11                         Guerrero  20308.96  20308.96  20308.96  20308.96
12                          Hidalgo   3657.31   3657.31   3657.31   3657.31
13                          Jalisco  14011.75  14011.75  14011.75  14011.75
14                           México   5504.66   5504.66   5504.66   5504.66
15                        Michoacán  32359.23  32359.23  32359.23  32359.23
16                          Morelos   1341.17   1341.17   1341.17   1341.17
17                          Nayarit  14337.48  14337.48  14337.48  14337.48
18                       Nuevo León   2038.46   2038.46   2038.46   2038.46
19                           Oaxaca  18347.35  18347.35  18347.35  18347.35
20                           Puebla   7424.43   7424.43   7424.43   7424.43
21                        Querétaro   1033.74   1033.74   1033.74   1033.74
22                     Quintana Roo   1250.52   1250.52   1250.52   1250.52
23                  San Luis Potosí   2691.29   2691.29   2691.29   2691.29
24                          Sinaloa  19924.23  19924.23  19924.23  19924.23
25                           Sonora  12000.74  12000.74  12000.74  12000.74
26                          Tabasco    689.66    689.66    689.66    689.66
27                       Tamaulipas   5910.18   5910.18   5910.18   5910.18
28                         Tlaxcala    281.08    281.08    281.08    281.08
29  Veracruz de Ignacio de la Llave  11370.24  11370.24  11370.24  11370.24
30                          Yucatán   2464.73   2464.73   2464.73   2464.73
31                        Zacatecas   1711.57   1711.57   1711.57   1711.57